"""Add Affiliate system models

Revision ID: 340b6535737c
Revises: 884a93d87330
Create Date: 2026-08-05 05:20:09.499661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340b6535737c'
down_revision: Union[str, None] = '884a93d87330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_affiliate_code'), ['affiliate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_id'), ['id'], unique=False)

    op.create_table('affiliate_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('clearance_status', sa.String(length=50), nullable=True),
    sa.Column('clearance_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    with op.batch_alter_table('affiliate_referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_referrals_id'), ['id'], unique=False)

    op.create_table('affiliate_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_withdrawals_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_withdrawals_id'))

    op.drop_table('affiliate_withdrawals')
    with op.batch_alter_table('affiliate_referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_referrals_id'))

    op.drop_table('affiliate_referrals')
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_affiliate_code'))

    op.drop_table('affiliate_profiles')
    # ### end Alembic commands ###
